version: '3'
services:
  client:
    build: 
      dockerfile: Dockerfile
      context: .
    ports:
      - 3000:3000
    volumes:
      - /node_modules
      - ./:/app
    environment:
      - REACT_APP_WEATHER_API: ${REACT_APP_WEATHER_API}