version: 2.1
jobs:
  build-and-test:
    working_directory: ~/repo
    docker:
      - image: cimg/node:16.13.2
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build React App
          command: yarn build
      - save_cache:
          key: app-build-cache-{{ .Branch }}
          paths:
            - ./build
      - persist_to_workspace:
          root: .
          paths:
            - .
      - run:
          name: Unit tests
          command: yarn test
  deploy:
    working_directory: ~/repo
    docker:
      - image: innovatorjapan/awscli:latest
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy
          command: 
            aws s3 sync build s3://$S3_BUCKET_NAME --delete --exact-timestamps;
workflows:
  version: 2
  build-deploy:
    jobs:
      - build-and-test:
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - master